/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/data360/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data based on provided filters
         * @description Retrieves dataset or indicators data based on a range of query filters.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description Unique identifier for the database.
                     * @example WB_WDI
                     */
                    DATABASE_ID: components["parameters"]["databaseIdQuery"];
                    /**
                     * @description Indicator ID.
                     * @example WB_WDI_SP_POP_TOTL
                     */
                    INDICATOR?: components["parameters"]["indicatorQuery"];
                    /**
                     * @description Reference area code (e.g., country code).
                     * @example
                     */
                    REF_AREA?: components["parameters"]["refAreaQuery"];
                    /**
                     * @description Sex of the subjects, if applicable.
                     * @example
                     */
                    SEX?: components["parameters"]["sexQuery"];
                    /**
                     * @description Age group filter.
                     * @example
                     */
                    AGE?: components["parameters"]["ageQuery"];
                    /**
                     * @description Urbanisation filter.
                     * @example
                     */
                    URBANISATION?: components["parameters"]["urbanisationQuery"];
                    /**
                     * @description Indicator specific dimension.
                     * @example
                     */
                    COMP_BREAKDOWN_1?: components["parameters"]["compBreakdown1Query"];
                    /**
                     * @description Indicator specific dimensionn.
                     * @example
                     */
                    COMP_BREAKDOWN_2?: components["parameters"]["compBreakdown2Query"];
                    /**
                     * @description Indicator specific dimensionn.
                     * @example
                     */
                    COMP_BREAKDOWN_3?: components["parameters"]["compBreakdown3Query"];
                    /**
                     * @description Time period for the data.
                     * @example
                     */
                    TIME_PERIOD?: components["parameters"]["timePeriodQuery"];
                    /**
                     * @description Frequency of the data.
                     * @example
                     */
                    FREQ?: components["parameters"]["freqQuery"];
                    /**
                     * @description Unit of measure for the data.
                     * @example
                     */
                    UNIT_MEASURE?: components["parameters"]["unitMeasureQuery"];
                    /**
                     * @description Type of unit (e.g., 'currency', 'percentage').
                     * @example
                     */
                    UNIT_TYPE?: components["parameters"]["unitTypeQuery"];
                    /**
                     * @description Multiplier for the unit.
                     * @example
                     */
                    UNIT_MULT?: components["parameters"]["unitMultQuery"];
                    /**
                     * @description Start of the time period range.
                     * @example
                     */
                    timePeriodFrom?: components["parameters"]["timePeriodFromQuery"];
                    /**
                     * @description End of the time period range.
                     * @example
                     */
                    timePeriodTo?: components["parameters"]["timePeriodToQuery"];
                    /**
                     * @description Number of records to skip. Each API call returns a maximum of 1000 records. Use the skip parameter to paginate through the results.
                     * @example 0
                     */
                    skip?: components["parameters"]["skipQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success. Returns the total count of matching records along with an array of data objects. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataResponse"];
                        "text/plain": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data360/disaggregation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Disaggregations for a given indicator
         * @description Returns all possible disaggregations for a specific indicator.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description Unique identifier for the dataset.
                     * @example WB_WDI
                     */
                    datasetId: components["parameters"]["datasetIdQueryDisag"];
                    /**
                     * @description Indicator ID.
                     * @example WB_WDI_SP_POP_TOTL
                     */
                    indicatorId?: components["parameters"]["indicatorQueryDisag"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data360/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List of indicator IDs
         * @description Retrieves a list of indicators available in a given dataset.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description Unique identifier for the database.
                     * @example WB_WDI
                     */
                    datasetId: components["parameters"]["datasetIdQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data360/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Metadata based on provided filters
         * @description Retrieves metadata based on a range of query filters.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description A JSON object containing a single 'query' property with the raw search query string. The query string follows standard syntax for filtering and selecting fields. */
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The complete search query string. This string should include all query parameters using the supported syntax. For example: "*&$filter=series_description/database_id eq 'WB_WDI'&$select=series_description/database_id,series_description/idno" */
                        query: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data360/searchv2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search function
         * @description Performs a search of Data360 based on the search parameters.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Vector search query parameters. Only the minimal set is shown in the example. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SearchQuerySchema"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SearchQuerySchema: {
            /**
             * @description When set to true, the response will include the total count of matching results.
             * @example true
             */
            count?: boolean;
            /**
             * @description A filter expression to narrow down the search results. Remove from the body of the request if no filtering needed.
             * @example series_description/topics/any(t: t/name eq 'Infrastructure: Transportation')
             */
            filter?: string;
            /**
             * @description Specifies the ordering of the results. Leave empty to apply default ordering.
             * @example series_description/name
             */
            orderby?: string;
            /**
             * @description A comma-separated list of fields to include in the response.
             * @example series_description/idno, series_description/name, series_description/database_id
             */
            select?: string;
            /**
             * @description Specifies which fields should be searched. Leave empty to search all available fields.
             * @example series_description/name
             */
            searchFields?: string;
            /**
             * @description The search term to be applied.
             * @example poverty
             */
            search?: string;
            /**
             * Format: int32
             * @description The maximum number of results to return.
             * @example 5
             */
            top?: number;
            /**
             * Format: int32
             * @description The number of results to skip, useful for pagination.
             * @example 0
             */
            skip?: number;
            facets?: string[] | null;
            vectorFilterModeSearch?: string | null;
            vectorQueries?: components["schemas"]["VectorQueryModel"][] | null;
        };
        Threshold: {
            kind?: string | null;
            /** Format: double */
            value?: number | null;
        };
        VectorQueryModel: {
            vector?: number[] | null;
            fields?: string | null;
            kind?: string | null;
            /** Format: int32 */
            k?: number | null;
            /** Format: double */
            weight?: number | null;
            threshold?: components["schemas"]["Threshold"];
        };
        DataResponse: {
            /** @description Total number of matching records. */
            count?: number;
            /** @description Array of data records. */
            value?: {
                /** @description Observation value. */
                OBS_VALUE?: string;
                /** @description Time format, e.g., period (P1Y). */
                TIME_FORMAT?: string;
                /** @description Multiplier for the unit. */
                UNIT_MULT?: number;
                /** @description Comment for the observation. */
                COMMENT_OBS?: string | null;
                /** @description Observation status. */
                OBS_STATUS?: string;
                /** @description Observation confidence. */
                OBS_CONF?: string;
                /** @description Aggregation method. */
                AGG_METHOD?: string;
                /** @description Number of decimal places. */
                DECIMALS?: string;
                /** @description Comment on the timeseries. */
                COMMENT_TS?: string;
                /** @description Identifier for the data source. */
                DATA_SOURCE?: string;
                /** @description Indicates if the data is the latest available. */
                LATEST_DATA?: boolean;
                /** @description Identifier for the database. */
                DATABASE_ID?: string;
                /** @description Identifier for the indicator. */
                INDICATOR?: string;
                /** @description Reference area (e.g., country or region code). */
                REF_AREA?: string;
                /** @description Sex of the subject. */
                SEX?: string;
                /** @description Age group. */
                AGE?: string;
                /** @description Indicator of urbanisation. */
                URBANISATION?: string;
                /** @description Composite breakdown dimension 1. */
                COMP_BREAKDOWN_1?: string;
                /** @description Composite breakdown dimension 2. */
                COMP_BREAKDOWN_2?: string;
                /** @description Composite breakdown dimension 3. */
                COMP_BREAKDOWN_3?: string;
                /** @description Time period of the observation. */
                TIME_PERIOD?: string;
                /** @description Frequency of the data. */
                FREQ?: string;
                /** @description Unit of measure. */
                UNIT_MEASURE?: string;
                /** @description Type of unit (if applicable). */
                UNIT_TYPE?: string | null;
            }[];
        };
    };
    responses: never;
    parameters: {
        /**
         * @description Unique identifier for the database.
         * @example WB_WDI
         */
        databaseIdQuery: string;
        /**
         * @description Unique identifier for the database.
         * @example WB_WDI
         */
        databaseIdQueryInd: string;
        /**
         * @description Unique identifier for the database.
         * @example WB_WDI
         */
        datasetIdQuery: string;
        /**
         * @description Maximum number of records to return.
         * @example 20
         */
        topQuery: number;
        /**
         * @description Number of records to skip. Each API call returns a maximum of 1000 records. Use the skip parameter to paginate through the results.
         * @example 0
         */
        skipQuery: number;
        /**
         * @description Indicator ID.
         * @example WB_WDI_SP_POP_TOTL
         */
        indicatorQuery: string;
        /**
         * @description Indicator ID.
         * @example WB_WDI_SP_POP_TOTL
         */
        indicatorQueryDisag: string;
        /**
         * @description Reference area code (e.g., country code).
         * @example
         */
        refAreaQuery: string;
        /**
         * @description Sex of the subjects, if applicable.
         * @example
         */
        sexQuery: string;
        /**
         * @description Age group filter.
         * @example
         */
        ageQuery: string;
        /**
         * @description Urbanisation filter.
         * @example
         */
        urbanisationQuery: string;
        /**
         * @description Indicator specific dimension.
         * @example
         */
        compBreakdown1Query: string;
        /**
         * @description Indicator specific dimensionn.
         * @example
         */
        compBreakdown2Query: string;
        /**
         * @description Indicator specific dimensionn.
         * @example
         */
        compBreakdown3Query: string;
        /**
         * @description Time period for the data.
         * @example
         */
        timePeriodQuery: string;
        /**
         * @description Frequency of the data.
         * @example
         */
        freqQuery: string;
        /**
         * @description Unit of measure for the data.
         * @example
         */
        unitMeasureQuery: string;
        /**
         * @description Type of unit (e.g., 'currency', 'percentage').
         * @example
         */
        unitTypeQuery: string;
        /**
         * @description Multiplier for the unit.
         * @example
         */
        unitMultQuery: string;
        /**
         * @description Start of the time period range.
         * @example
         */
        timePeriodFromQuery: string;
        /**
         * @description End of the time period range.
         * @example
         */
        timePeriodToQuery: string;
        /**
         * @description Type of bond, if applicable.
         * @example
         */
        bondTypeQuery: string;
        /**
         * @description Bucket for the bond tenor.
         * @example
         */
        tenorBucketQuery: string;
        /**
         * @description Type of issuer.
         * @example
         */
        issuerTypeQuery: string;
        /**
         * @description Name of the issuer.
         * @example
         */
        issNameQuery: string;
        /**
         * @description International Securities Identification Number.
         * @example
         */
        isinQuery: string;
        /**
         * @description Tenor of the bond.
         * @example
         */
        tenorQuery: string;
        /**
         * @description Outstanding value, if applicable.
         * @example
         */
        outstandingQuery: string;
        /**
         * @description Deal size for the bond issuance.
         * @example
         */
        dealSizeQuery: string;
        /**
         * @description Metric to be used for the data.
         * @example
         */
        metricQuery: string;
        /**
         * @description Currency code (e.g., USD, EUR).
         * @example
         */
        currencyQuery: string;
        /**
         * @description Issue date of the bond.
         * @example
         */
        dateIssQuery: string;
        /**
         * @description Maturity date of the bond.
         * @example
         */
        dateMatQuery: string;
        /**
         * @description Flag indicating whether to retrieve the latest data.
         * @example
         */
        isLatestDataQuery: boolean | null;
        /**
         * @description Response format, e.g., json.
         * @example
         */
        formatQuery: string;
        /**
         * @description Fields to select in the response.
         * @example
         */
        selectQuery: string;
        /**
         * @description Filter criteria for the data.
         * @example
         */
        filterQuery: string;
        /**
         * @description Unique identifier for the dataset.
         * @example WB_WDI
         */
        datasetIdQueryDisag: string;
        /**
         * @description Unique identifier for the indicator.
         * @example WB_WDI_SP_POP_TOTL
         */
        indicatorIdQuery: string;
        /**
         * @description Type of user action to filter by.
         * @example click
         */
        actionTypeQuery: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
